### ISSUE TITLE
IPQ60xx编译正常，但是编译R7800时出现找不到nss_arch.h错误

### ISSUE THREAD

**Issue by hzjnet** [LiBwrt-op/openwrt-6.x#18]
make -C "/openwrt/openwrt-6.x-nss-git-breeze303-20240718-fLiBwrt-2-ipq806x/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/linux-ipq806x_generic/linux-6.6.40" NSS_DRV_CLMAP_ENABLE=n NSS_DRV_DTLS_ENABLE=n NSS_DRV_GRE_REDIR_ENABLE=n NSS_DRV_GRE_TUNNEL_ENABLE=n NSS_DRV_IPV4_REASM_ENABLE=n NSS_DRV_IPV6_REASM_ENABLE=n NSS_DRV_LAG_ENABLE=n NSS_DRV_OAM_ENABLE=n NSS_DRV_PORTID_ENABLE=n NSS_DRV_QRFS_ENABLE=n NSS_DRV_QVPN_ENABLE=n NSS_DRV_OVPN_ENABLE=n NSS_DRV_SJACK_ENABLE=n NSS_DRV_TLS_ENABLE=n NSS_DRV_TRUSTSEC_ENABLE=n NSS_DRV_TRUSTSEC_RX_ENABLE=n NSS_DRV_TSTAMP_ENABLE=n NSS_DRV_VLAN_ENABLE=n NSS_DRV_WIFI_EXT_VDEV_ENABLE=n NSS_DRV_UDP_ST_ENABLE=n NSS_DRV_CAPWAP_ENABLE=n NSS_DRV_LSO_RX_ENABLE=n NSS_DRV_WIFI_LEGACY_ENABLE=n CROSS_COMPILE="arm-openwrt-linux-muslgnueabi-" ARCH="arm" M="/openwrt/openwrt-6.x-nss-git-breeze303-20240718-fLiBwrt-2-ipq806x/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/linux-ipq806x_generic/qca-nss-drv-12.5.2024.04.06~53a0dc1" EXTRA_CFLAGS="-I/openwrt/openwrt-6.x-nss-git-breeze303-20240718-fLiBwrt-2-ipq806x/staging_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/usr/include/qca-nss-dp -I/openwrt/openwrt-6.x-nss-git-breeze303-20240718-fLiBwrt-2-ipq806x/staging_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/usr/include/qca-ssdk -Wno-unused-variable -Wno-enum-conversion -DNSS_MEM_PROFILE_MEDIUM" SoC= KCFLAGS="-fmacro-prefix-map=/openwrt/openwrt-6.x-nss-git-breeze303-20240718-fLiBwrt-2-ipq806x/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi=target-arm_cortex-a15+neon-vfpv4_musl_eabi -fno-caller-saves " HOSTCFLAGS="-O2 -I/openwrt/openwrt-6.x-nss-git-breeze303-20240718-fLiBwrt-2-ipq806x/staging_dir/host/include -I/openwrt/openwrt-6.x-nss-git-breeze303-20240718-fLiBwrt-2-ipq806x/staging_dir/hostpkg/include -I/openwrt/openwrt-6.x-nss-git-breeze303-20240718-fLiBwrt-2-ipq806x/staging_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/host/include -Wall -Wmissing-prototypes -Wstrict-prototypes" CROSS_COMPILE="arm-openwrt-linux-muslgnueabi-" ARCH="arm" KBUILD_HAVE_NLS=no KBUILD_BUILD_USER="" KBUILD_BUILD_HOST="" KBUILD_BUILD_TIMESTAMP="Thu Jul 18 10:16:03 2024" KBUILD_BUILD_VERSION="0" KBUILD_HOSTLDFLAGS="-L/openwrt/openwrt-6.x-nss-git-breeze303-20240718-fLiBwrt-2-ipq806x/staging_dir/host/lib" CONFIG_SHELL="bash" V=''  cmd_syscalls= KBUILD_EXTRA_SYMBOLS="/openwrt/openwrt-6.x-nss-git-breeze303-20240718-fLiBwrt-2-ipq806x/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/linux-ipq806x_generic/symvers/cryptodev-linux.symvers /openwrt/openwrt-6.x-nss-git-breeze303-20240718-fLiBwrt-2-ipq806x/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/linux-ipq806x_generic/symvers/gpio-button-hotplug.symvers /openwrt/openwrt-6.x-nss-git-breeze303-20240718-fLiBwrt-2-ipq806x/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/linux-ipq806x_generic/symvers/fullconenat-nft.symvers" CC="ccache arm-openwrt-linux-muslgnueabi-gcc" KERNELRELEASE=6.6.40  modules
make[4]: Entering directory '/openwrt/openwrt-6.x-nss-git-breeze303-20240718-fLiBwrt-2-ipq806x/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/linux-ipq806x_generic/linux-6.6.40'
  CC [M]  /openwrt/openwrt-6.x-nss-git-breeze303-20240718-fLiBwrt-2-ipq806x/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/linux-ipq806x_generic/qca-nss-drv-12.5.2024.04.06~53a0dc1/nss_cmn.o
In file included from /openwrt/openwrt-6.x-nss-git-breeze303-20240718-fLiBwrt-2-ipq806x/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/linux-ipq806x_generic/qca-nss-drv-12.5.2024.04.06~53a0dc1/nss_core.h:40,
                 from /openwrt/openwrt-6.x-nss-git-breeze303-20240718-fLiBwrt-2-ipq806x/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/linux-ipq806x_generic/qca-nss-drv-12.5.2024.04.06~53a0dc1/nss_hal/include/nss_hal.h:29,
                 from /openwrt/openwrt-6.x-nss-git-breeze303-20240718-fLiBwrt-2-ipq806x/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/linux-ipq806x_generic/qca-nss-drv-12.5.2024.04.06~53a0dc1/nss_tx_rx_common.h:25,
                 from /openwrt/openwrt-6.x-nss-git-breeze303-20240718-fLiBwrt-2-ipq806x/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/linux-ipq806x_generic/qca-nss-drv-12.5.2024.04.06~53a0dc1/nss_cmn.c:26:
/openwrt/openwrt-6.x-nss-git-breeze303-20240718-fLiBwrt-2-ipq806x/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/linux-ipq806x_generic/qca-nss-drv-12.5.2024.04.06~53a0dc1/exports/nss_api_if.h:36:10: fatal error: nss_arch.h: No such file or directory
   36 | #include "nss_arch.h"
      |          ^~~~~~~~~~~~
compilation terminated.
make[6]: *** [scripts/Makefile.build:243: /openwrt/openwrt-6.x-nss-git-breeze303-20240718-fLiBwrt-2-ipq806x/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/linux-ipq806x_generic/qca-nss-drv-12.5.2024.04.06~53a0dc1/nss_cmn.o] Error 1
make[5]: *** [/openwrt/openwrt-6.x-nss-git-breeze303-20240718-fLiBwrt-2-ipq806x/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/linux-ipq806x_generic/linux-6.6.40/Makefile:1921: /openwrt/openwrt-6.x-nss-git-breeze303-20240718-fLiBwrt-2-ipq806x/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/linux-ipq806x_generic/qca-nss-drv-12.5.2024.04.06~53a0dc1] Error 2
make[4]: *** [Makefile:234: __sub-make] Error 2
make[4]: Leaving directory '/openwrt/openwrt-6.x-nss-git-breeze303-20240718-fLiBwrt-2-ipq806x/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/linux-ipq806x_generic/linux-6.6.40'
make[3]: *** [Makefile:360: /openwrt/openwrt-6.x-nss-git-breeze303-20240718-fLiBwrt-2-ipq806x/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/linux-ipq806x_generic/qca-nss-drv-12.5.2024.04.06~53a0dc1/.built] Error 2
make[3]: Leaving directory '/openwrt/openwrt-6.x-nss-git-breeze303-20240718-fLiBwrt-2-ipq806x/feeds/nss_packages/qca-nss-drv'
time: package/feeds/nss_packages/qca-nss-drv/compile#1.05#0.20#1.27
    ERROR: package/feeds/nss_packages/qca-nss-drv failed to build.
make[2]: *** [package/Makefile:173: package/feeds/nss_packages/qca-nss-drv/compile] Error 1

**Comment by hzjnet** [comment]
找到对应nss_ipq806x.h后修改链接编译如下错误，应该是没有对ipq806x做适配吧：

make[4]: Entering directory '/openwrt/openwrt-6.x-nss-git-breeze303-20240718-fqosmio.feeds/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/linux-ipq806x_generic/linux-6.6.40'
  CC [M]  /openwrt/openwrt-6.x-nss-git-breeze303-20240718-fqosmio.feeds/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/linux-ipq806x_generic/qca-nss-drv-12.5.2024.04.06~53a0dc1/nss_cmn.o
In file included from /openwrt/openwrt-6.x-nss-git-breeze303-20240718-fqosmio.feeds/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/linux-ipq806x_generic/qca-nss-drv-12.5.2024.04.06~53a0dc1/nss_core.h:40,
                 from /openwrt/openwrt-6.x-nss-git-breeze303-20240718-fqosmio.feeds/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/linux-ipq806x_generic/qca-nss-drv-12.5.2024.04.06~53a0dc1/nss_hal/include/nss_hal.h:29,
                 from /openwrt/openwrt-6.x-nss-git-breeze303-20240718-fqosmio.feeds/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/linux-ipq806x_generic/qca-nss-drv-12.5.2024.04.06~53a0dc1/nss_tx_rx_common.h:25,
                 from /openwrt/openwrt-6.x-nss-git-breeze303-20240718-fqosmio.feeds/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/linux-ipq806x_generic/qca-nss-drv-12.5.2024.04.06~53a0dc1/nss_cmn.c:26:
/openwrt/openwrt-6.x-nss-git-breeze303-20240718-fqosmio.feeds/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/linux-ipq806x_generic/qca-nss-drv-12.5.2024.04.06~53a0dc1/exports/nss_api_if.h:36:10: fatal error: nss_arch.h: No such file or directory
   36 | #include "nss_arch.h"
      |          ^~~~~~~~~~~~
compilation terminated.
make[6]: *** [scripts/Makefile.build:243: /openwrt/openwrt-6.x-nss-git-breeze303-20240718-fqosmio.feeds/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/linux-ipq806x_generic/qca-nss-drv-12.5.2024.04.06~53a0dc1/nss_cmn.o] Error 1
make[5]: *** [/openwrt/openwrt-6.x-nss-git-breeze303-20240718-fqosmio.feeds/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/linux-ipq806x_generic/linux-6.6.40/Makefile:1921: /openwrt/openwrt-6.x-nss-git-breeze303-20240718-fqosmio.feeds/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/linux-ipq806x_generic/qca-nss-drv-12.5.2024.04.06~53a0dc1] Error 2
make[4]: *** [Makefile:234: __sub-make] Error 2
make[3]: *** [Makefile:360: /openwrt/openwrt-6.x-nss-git-breeze303-20240718-fqosmio.feeds/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/linux-ipq806x_generic/qca-nss-drv-12.5.2024.04.06~53a0dc1/.built] Error 2
make[4]: Leaving directory '/openwrt/openwrt-6.x-nss-git-breeze303-20240718-fqosmio.feeds/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/linux-ipq806x_generic/linux-6.6.40'
make[3]: Leaving directory '/openwrt/openwrt-6.x-nss-git-breeze303-20240718-fqosmio.feeds/feeds/nss_packages/qca-nss-drv'
time: package/feeds/nss_packages/qca-nss-drv/compile#0.82#0.19#1.00
    ERROR: package/feeds/nss_packages/qca-nss-drv failed to build.

cd build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/linux-ipq806x_generic/qca-nss-drv-12.5.2024.04.06~53a0dc1/exports/
ll
nss_arch.h -> arch/nss_.h
rm -rf nss_arch.h
ln -s arch/nss_ipq806x.h nss_arch.h

make[4]: Entering directory '/openwrt/openwrt-6.x-nss-git-breeze303-20240718-fqosmio.feeds/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/linux-ipq806x_generic/linux-6.6.40'
  CC [M]  /openwrt/openwrt-6.x-nss-git-breeze303-20240718-fqosmio.feeds/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/linux-ipq806x_generic/qca-nss-drv-12.5.2024.04.06~53a0dc1/nss_cmn.o
  CC [M]  /openwrt/openwrt-6.x-nss-git-breeze303-20240718-fqosmio.feeds/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/linux-ipq806x_generic/qca-nss-drv-12.5.2024.04.06~53a0dc1/nss_core.o
../qca-nss-drv-12.5.2024.04.06~53a0dc1/nss_core.c: In function 'nss_core_set_skb_classify':
../qca-nss-drv-12.5.2024.04.06~53a0dc1/nss_core.c:1111:17: error: implicit declaration of function 'skb_set_tc_classify_offload' [-Werror=implicit-function-declaration]
 1111 |                 skb_set_tc_classify_offload(nbuf);
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
make[6]: *** [scripts/Makefile.build:243: /openwrt/openwrt-6.x-nss-git-breeze303-20240718-fqosmio.feeds/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/linux-ipq806x_generic/qca-nss-drv-12.5.2024.04.06~53a0dc1/nss_core.o] Error 1
make[5]: *** [/openwrt/openwrt-6.x-nss-git-breeze303-20240718-fqosmio.feeds/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/linux-ipq806x_generic/linux-6.6.40/Makefile:1921: /openwrt/openwrt-6.x-nss-git-breeze303-20240718-fqosmio.feeds/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/linux-ipq806x_generic/qca-nss-drv-12.5.2024.04.06~53a0dc1] Error 2
make[4]: *** [Makefile:234: __sub-make] Error 2
make[4]: Leaving directory '/openwrt/openwrt-6.x-nss-git-breeze303-20240718-fqosmio.feeds/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/linux-ipq806x_generic/linux-6.6.40'
make[3]: *** [Makefile:360: /openwrt/openwrt-6.x-nss-git-breeze303-20240718-fqosmio.feeds/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/linux-ipq806x_generic/qca-nss-drv-12.5.2024.04.06~53a0dc1/.built] Error 2
make[3]: Leaving directory '/openwrt/openwrt-6.x-nss-git-breeze303-20240718-fqosmio.feeds/feeds/nss_packages/qca-nss-drv'
time: package/feeds/nss_packages/qca-nss-drv/compile#2.41#0.34#2.76
    ERROR: package/feeds/nss_packages/qca-nss-drv failed to build.
make[2]: *** [package/Makefile:173: package/feeds/nss_packages/qca-nss-drv/compile] Error 1

**Comment by breeze303** [comment]
是的，基本没用过ipq807x，也没修过
