### ISSUE TITLE
大佬 可以增加 xiaomi ax3600-stock分区吗

### ISSUE THREAD

**Issue by wxzy322** [LiBwrt-op/openwrt-6.x#21]
可以增加 xiaomi ax3600-stock分区吗  好多基友到手就刷了uboot  改为大分区    imm有stock分区固件  可是有没有nss     所以建议看闲了能增加个stock分区不

**Comment by breeze303** [comment]
晚点看看

**Comment by breeze303** [comment]
https://github.com/LiBwrt-op/openwrt-6.x/commit/347deed1c512f0d99d136bcba102dbfc6dd435a7#diff-d028c5e782700ba3dae3229e56da2518ac8ff430e9db7393b5c05071d1b363b6
加上了，你编译看看，不知道有没有漏东西

**Comment by wxzy322** [comment]
三克油  外瑞马驰

**Comment by wxzy322** [comment]
编译过了   刷进去 启动不了  ~

**Comment by breeze303** [comment]
有ttl吗，看不到日志也我也没机器只能云适配

**Comment by breeze303** [comment]
https://github.com/VIKINGYFY/immortalwrt.git或者你尝试下这个源码

**Comment by wxzy322** [comment]
嗯  这个是正常的     我用过你这个360 v6 的    觉得挺好   所以还想用你的源码

**Comment by breeze303** [comment]
那我应该是漏了代码，有空我排查下
