### ISSUE TITLE
opkg 上游是否不支持IPQ60xx ?

### ISSUE THREAD

**Issue by Albresky** [LiBwrt-op/openwrt-6.x#22]
作者你好，用你的仓库编译固件(**JDC AX1800 Pro, IPQ60xx系列**)后，发现 `opkg update` 报错：

```bash
root@OpenWrt:/var/log/smartdns# opkg update
Downloading https://mirrors.vsean.net/openwrt/snapshots/targets/qualcommax/ipq60xx/packages/Packages.gz
*** Failed to download the package list from https://mirrors.vsean.net/openwrt/snapshots/targets/qualcommax/ipq60xx/packages/Packages.gz

Downloading https://mirrors.vsean.net/openwrt/snapshots/packages/aarch64_cortex-a53/base/Packages.gz
Updated list of available packages in /var/opkg-lists/libwrt_base
Downloading https://mirrors.vsean.net/openwrt/snapshots/packages/aarch64_cortex-a53/luci/Packages.gz
Updated list of available packages in /var/opkg-lists/libwrt_luci
Downloading https://mirrors.vsean.net/openwrt/snapshots/packages/aarch64_cortex-a53/nss_packages/Packages.gz
*** Failed to download the package list from https://mirrors.vsean.net/openwrt/snapshots/packages/aarch64_cortex-a53/nss_packages/Packages.gz

Downloading https://mirrors.vsean.net/openwrt/snapshots/packages/aarch64_cortex-a53/packages/Packages.gz
Updated list of available packages in /var/opkg-lists/libwrt_packages
Downloading https://mirrors.vsean.net/openwrt/snapshots/packages/aarch64_cortex-a53/routing/Packages.gz
Updated list of available packages in /var/opkg-lists/libwrt_routing
Downloading https://mirrors.vsean.net/openwrt/snapshots/packages/aarch64_cortex-a53/sqm_scripts_nss/Packages.gz
*** Failed to download the package list from https://mirrors.vsean.net/openwrt/snapshots/packages/aarch64_cortex-a53/sqm_scripts_nss/Packages.gz

Downloading https://mirrors.vsean.net/openwrt/snapshots/packages/aarch64_cortex-a53/telephony/Packages.gz
Updated list of available packages in /var/opkg-lists/libwrt_telephony
Collected errors:
 * opkg_download: Failed to download https://mirrors.vsean.net/openwrt/snapshots/targets/qualcommax/ipq60xx/packages/Packages.gz, wget returned 8.
 * opkg_download: Failed to download https://mirrors.vsean.net/openwrt/snapshots/packages/aarch64_cortex-a53/nss_packages/Packages.gz, wget returned 8.
 * opkg_download: Failed to download https://mirrors.vsean.net/openwrt/snapshots/packages/aarch64_cortex-a53/sqm_scripts_nss/Packages.gz, wget returned 8.
 ```

排查后发现，失败的这些 url 在 `immortalwrt` 中并不存在。

`/etc/opkg/distfeeds.conf` 如下：
```
#src/gz libwrt_core https://mirrors.vsean.net/openwrt/snapshots/targets/qualcommax/ipq60xx/packages
src/gz libwrt_base https://mirrors.vsean.net/openwrt/snapshots/packages/aarch64_cortex-a53/base
src/gz libwrt_luci https://mirrors.vsean.net/openwrt/snapshots/packages/aarch64_cortex-a53/luci
#src/gz libwrt_nss_packages https://mirrors.vsean.net/openwrt/snapshots/packages/aarch64_cortex-a53/nss_packages
src/gz libwrt_packages https://mirrors.vsean.net/openwrt/snapshots/packages/aarch64_cortex-a53/packages
src/gz libwrt_routing https://mirrors.vsean.net/openwrt/snapshots/packages/aarch64_cortex-a53/routing
#src/gz libwrt_sqm_scripts_nss https://mirrors.vsean.net/openwrt/snapshots/packages/aarch64_cortex-a53/sqm_scripts_nss
src/gz libwrt_telephony https://mirrors.vsean.net/openwrt/snapshots/packages/aarch64_cortex-a53/telephony
```

注释掉的三条即报错的项目，这三项是否非必须的包？如果是必须的包，那正确的url是什么呢？

谢谢回复。

**Comment by VIKINGYFY** [comment]
没啥用，无视就行

**Comment by breeze303** [comment]
直接删除即可

**Comment by 363137946** [comment]
> 作者你好，用你的仓库编译固件(**JDC AX1800 Pro, IPQ60xx系列**)后，发现 `opkg update` 报错：
> 
> ```shell
> root@OpenWrt:/var/log/smartdns# opkg update
> Downloading https://mirrors.vsean.net/openwrt/snapshots/targets/qualcommax/ipq60xx/packages/Packages.gz
> *** Failed to download the package list from https://mirrors.vsean.net/openwrt/snapshots/targets/qualcommax/ipq60xx/packages/Packages.gz
> 
> Downloading https://mirrors.vsean.net/openwrt/snapshots/packages/aarch64_cortex-a53/base/Packages.gz
> Updated list of available packages in /var/opkg-lists/libwrt_base
> Downloading https://mirrors.vsean.net/openwrt/snapshots/packages/aarch64_cortex-a53/luci/Packages.gz
> Updated list of available packages in /var/opkg-lists/libwrt_luci
> Downloading https://mirrors.vsean.net/openwrt/snapshots/packages/aarch64_cortex-a53/nss_packages/Packages.gz
> *** Failed to download the package list from https://mirrors.vsean.net/openwrt/snapshots/packages/aarch64_cortex-a53/nss_packages/Packages.gz
> 
> Downloading https://mirrors.vsean.net/openwrt/snapshots/packages/aarch64_cortex-a53/packages/Packages.gz
> Updated list of available packages in /var/opkg-lists/libwrt_packages
> Downloading https://mirrors.vsean.net/openwrt/snapshots/packages/aarch64_cortex-a53/routing/Packages.gz
> Updated list of available packages in /var/opkg-lists/libwrt_routing
> Downloading https://mirrors.vsean.net/openwrt/snapshots/packages/aarch64_cortex-a53/sqm_scripts_nss/Packages.gz
> *** Failed to download the package list from https://mirrors.vsean.net/openwrt/snapshots/packages/aarch64_cortex-a53/sqm_scripts_nss/Packages.gz
> 
> Downloading https://mirrors.vsean.net/openwrt/snapshots/packages/aarch64_cortex-a53/telephony/Packages.gz
> Updated list of available packages in /var/opkg-lists/libwrt_telephony
> Collected errors:
>  * opkg_download: Failed to download https://mirrors.vsean.net/openwrt/snapshots/targets/qualcommax/ipq60xx/packages/Packages.gz, wget returned 8.
>  * opkg_download: Failed to download https://mirrors.vsean.net/openwrt/snapshots/packages/aarch64_cortex-a53/nss_packages/Packages.gz, wget returned 8.
>  * opkg_download: Failed to download https://mirrors.vsean.net/openwrt/snapshots/packages/aarch64_cortex-a53/sqm_scripts_nss/Packages.gz, wget returned 8.
> ```
> 
> 排查后发现，失败的这些 url 在 `immortalwrt` 中并不存在。
> 
> `/etc/opkg/distfeeds.conf` 如下：
> 
> ```
> #src/gz libwrt_core https://mirrors.vsean.net/openwrt/snapshots/targets/qualcommax/ipq60xx/packages
> src/gz libwrt_base https://mirrors.vsean.net/openwrt/snapshots/packages/aarch64_cortex-a53/base
> src/gz libwrt_luci https://mirrors.vsean.net/openwrt/snapshots/packages/aarch64_cortex-a53/luci
> #src/gz libwrt_nss_packages https://mirrors.vsean.net/openwrt/snapshots/packages/aarch64_cortex-a53/nss_packages
> src/gz libwrt_packages https://mirrors.vsean.net/openwrt/snapshots/packages/aarch64_cortex-a53/packages
> src/gz libwrt_routing https://mirrors.vsean.net/openwrt/snapshots/packages/aarch64_cortex-a53/routing
> #src/gz libwrt_sqm_scripts_nss https://mirrors.vsean.net/openwrt/snapshots/packages/aarch64_cortex-a53/sqm_scripts_nss
> src/gz libwrt_telephony https://mirrors.vsean.net/openwrt/snapshots/packages/aarch64_cortex-a53/telephony
> ```
> 
> 注释掉的三条即报错的项目，这三项是否非必须的包？如果是必须的包，那正确的url是什么呢？
> 
> 谢谢回复。

你的固件挺好用，本地编译的吗，能云编译就好了

**Comment by Albresky** [comment]
> > 作者你好，用你的仓库编译固件(**JDC AX1800 Pro, IPQ60xx系列**)后，发现 `opkg update` 报错：
> > ```shell
> > root@OpenWrt:/var/log/smartdns# opkg update
> > Downloading https://mirrors.vsean.net/openwrt/snapshots/targets/qualcommax/ipq60xx/packages/Packages.gz
> > *** Failed to download the package list from https://mirrors.vsean.net/openwrt/snapshots/targets/qualcommax/ipq60xx/packages/Packages.gz
> > 
> > Downloading https://mirrors.vsean.net/openwrt/snapshots/packages/aarch64_cortex-a53/base/Packages.gz
> > Updated list of available packages in /var/opkg-lists/libwrt_base
> > Downloading https://mirrors.vsean.net/openwrt/snapshots/packages/aarch64_cortex-a53/luci/Packages.gz
> > Updated list of available packages in /var/opkg-lists/libwrt_luci
> > Downloading https://mirrors.vsean.net/openwrt/snapshots/packages/aarch64_cortex-a53/nss_packages/Packages.gz
> > *** Failed to download the package list from https://mirrors.vsean.net/openwrt/snapshots/packages/aarch64_cortex-a53/nss_packages/Packages.gz
> > 
> > Downloading https://mirrors.vsean.net/openwrt/snapshots/packages/aarch64_cortex-a53/packages/Packages.gz
> > Updated list of available packages in /var/opkg-lists/libwrt_packages
> > Downloading https://mirrors.vsean.net/openwrt/snapshots/packages/aarch64_cortex-a53/routing/Packages.gz
> > Updated list of available packages in /var/opkg-lists/libwrt_routing
> > Downloading https://mirrors.vsean.net/openwrt/snapshots/packages/aarch64_cortex-a53/sqm_scripts_nss/Packages.gz
> > *** Failed to download the package list from https://mirrors.vsean.net/openwrt/snapshots/packages/aarch64_cortex-a53/sqm_scripts_nss/Packages.gz
> > 
> > Downloading https://mirrors.vsean.net/openwrt/snapshots/packages/aarch64_cortex-a53/telephony/Packages.gz
> > Updated list of available packages in /var/opkg-lists/libwrt_telephony
> > Collected errors:
> >  * opkg_download: Failed to download https://mirrors.vsean.net/openwrt/snapshots/targets/qualcommax/ipq60xx/packages/Packages.gz, wget returned 8.
> >  * opkg_download: Failed to download https://mirrors.vsean.net/openwrt/snapshots/packages/aarch64_cortex-a53/nss_packages/Packages.gz, wget returned 8.
> >  * opkg_download: Failed to download https://mirrors.vsean.net/openwrt/snapshots/packages/aarch64_cortex-a53/sqm_scripts_nss/Packages.gz, wget returned 8.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 排查后发现，失败的这些 url 在 `immortalwrt` 中并不存在。
> > `/etc/opkg/distfeeds.conf` 如下：
> > ```
> > #src/gz libwrt_core https://mirrors.vsean.net/openwrt/snapshots/targets/qualcommax/ipq60xx/packages
> > src/gz libwrt_base https://mirrors.vsean.net/openwrt/snapshots/packages/aarch64_cortex-a53/base
> > src/gz libwrt_luci https://mirrors.vsean.net/openwrt/snapshots/packages/aarch64_cortex-a53/luci
> > #src/gz libwrt_nss_packages https://mirrors.vsean.net/openwrt/snapshots/packages/aarch64_cortex-a53/nss_packages
> > src/gz libwrt_packages https://mirrors.vsean.net/openwrt/snapshots/packages/aarch64_cortex-a53/packages
> > src/gz libwrt_routing https://mirrors.vsean.net/openwrt/snapshots/packages/aarch64_cortex-a53/routing
> > #src/gz libwrt_sqm_scripts_nss https://mirrors.vsean.net/openwrt/snapshots/packages/aarch64_cortex-a53/sqm_scripts_nss
> > src/gz libwrt_telephony https://mirrors.vsean.net/openwrt/snapshots/packages/aarch64_cortex-a53/telephony
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 注释掉的三条即报错的项目，这三项是否非必须的包？如果是必须的包，那正确的url是什么呢？
> > 谢谢回复。
> 
> 你的固件挺好用，本地编译的吗，能云编译就好了

---

前人栽树，我只是做了些 configuration 的工作。有空了后面可能会考虑加到 Github Actions 进行云编译。LiBwrt 应该是有维护云编译的 repo。

本地二次编译也还是挺快的（16 核心 CPU）。

追求新其实没太大必要，稳定是第一位的。
