### ISSUE TITLE
大佬，ipq807x 系列编译还是不通过，麻烦修修

### ISSUE THREAD

**Issue by wxzy322** [LiBwrt-op/openwrt-6.x#29]
make[3] -C target/linux compile
    ERROR: target/linux failed to build.
make -r world: build failed. Please re-run make with -j1 V=s or V=sc for a higher verbosity level to see what's going on
make: *** [/home/runner/work/openwrt-ci2/openwrt-ci2/openwrt/include/toplevel.mk:248: world] Error 1
WARNING: Makefile 'package/feeds/smpackage/luci-app-bandwidthd/Makefile' has a dependency on 'bandwidthd', which does not exist
WARNING: Makefile 'package/feeds/smpackage/luci-app-bypass/Makefile' has a dependency on 'shadowsocks-libev-ss-server', which does not exist
WARNING: Makefile 'package/feeds/smpackage/luci-app-bypass/Makefile' has a dependency on 'shadowsocks-libev-ss-local', which does not exist
WARNING: Makefile 'package/feeds/smpackage/luci-app-bypass/Makefile' has a dependency on 'shadowsocks-libev-ss-redir', which does not exist
WARNING: Makefile 'package/feeds/smpackage/luci-app-gowebdav/Makefile' has a dependency on 'gowebdav', which does not exist
WARNING: Makefile 'package/feeds/smpackage/luci-app-ssr-plus/Makefile' has a dependency on 'shadowsocks-libev-ss-local', which does not exist
WARNING: Makefile 'package/feeds/smpackage/luci-app-ssr-plus/Makefile' has a dependency on 'shadowsocks-libev-ss-redir', which does not exist
WARNING: Makefile 'package/feeds/smpackage/luci-app-ssr-plus/Makefile' has a dependency on 'shadowsocks-libev-ss-server', which does not exist
WARNING: Makefile 'package/feeds/smpackage/natflow/Makefile' has a dependency on 'urllogger', which does not exist
make[2]: Entering directory '/home/runner/work/openwrt-ci2/openwrt-ci2/openwrt/scripts/config'
make[2]: 'conf' is up to date.
make[2]: Leaving directory '/home/runner/work/openwrt-ci2/openwrt-ci2/openwrt/scripts/config'
make[1]: Entering directory '/home/runner/work/openwrt-ci2/openwrt-ci2/openwrt'
make[2]: Entering directory '/home/runner/work/openwrt-ci2/openwrt-ci2/openwrt'
+ mkdir -p /home/runner/work/openwrt-ci2/openwrt-ci2/openwrt/staging_dir/target-aarch64_cortex-a53_musl
+ cd /home/runner/work/openwrt-ci2/openwrt-ci2/openwrt/staging_dir/target-aarch64_cortex-a53_musl
+ mkdir -p bin lib stamp usr/include usr/lib
mkdir -p /home/runner/work/openwrt-ci2/openwrt-ci2/openwrt/build_dir/target-aarch64_cortex-a53_musl/stamp
touch /home/runner/work/openwrt-ci2/openwrt-ci2/openwrt/staging_dir/target-aarch64_cortex-a53_musl/.prepared
make[3]: Entering directory '/home/runner/work/openwrt-ci2/openwrt-ci2/openwrt/target/linux'
make[4]: Entering directory '/home/runner/work/openwrt-ci2/openwrt-ci2/openwrt/target/linux/qualcommax'
rm -f /home/runner/work/openwrt-ci2/openwrt-ci2/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-qualcommax_ipq807x/linux-6.6.50/localversion
/home/runner/work/openwrt-ci2/openwrt-ci2/openwrt/scripts/kconfig.pl  + + /home/runner/work/openwrt-ci2/openwrt-ci2/openwrt/target/linux/generic/config-6.6 /home/runner/work/openwrt-ci2/openwrt-ci2/openwrt/target/linux/qualcommax/config-6.6 /home/runner/work/openwrt-ci2/openwrt-ci2/openwrt/target/linux/qualcommax/ipq807x/config-default > /home/runner/work/openwrt-ci2/openwrt-ci2/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-qualcommax_ipq807x/linux-6.6.50/.config.target
awk '/^(#[[:space:]]+)?CONFIG_KERNEL/{sub("CONFIG_KERNEL_","CONFIG_");print}' /home/runner/work/openwrt-ci2/openwrt-ci2/openwrt/.config >> /home/runner/work/openwrt-ci2/openwrt-ci2/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-qualcommax_ipq807x/linux-6.6.50/.config.target
echo "# CONFIG_KALLSYMS_EXTRA_PASS is not set" >> /home/runner/work/openwrt-ci2/openwrt-ci2/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-qualcommax_ipq807x/linux-6.6.50/.config.target
echo "# CONFIG_KALLSYMS_ALL is not set" >> /home/runner/work/openwrt-ci2/openwrt-ci2/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-qualcommax_ipq807x/linux-6.6.50/.config.target
echo "CONFIG_KALLSYMS_UNCOMPRESSED=y" >> /home/runner/work/openwrt-ci2/openwrt-ci2/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-qualcommax_ipq807x/linux-6.6.50/.config.target
/home/runner/work/openwrt-ci2/openwrt-ci2/openwrt/scripts/package-metadata.pl kconfig /home/runner/work/openwrt-ci2/openwrt-ci2/openwrt/tmp/.packageinfo /home/runner/work/openwrt-ci2/openwrt-ci2/openwrt/.config 6.6 > /home/runner/work/openwrt-ci2/openwrt-ci2/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-qualcommax_ipq807x/linux-6.6.50/.config.override
/home/runner/work/openwrt-ci2/openwrt-ci2/openwrt/scripts/kconfig.pl 'm+' '+' /home/runner/work/openwrt-ci2/openwrt-ci2/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-qualcommax_ipq807x/linux-6.6.50/.config.target /dev/null /home/runner/work/openwrt-ci2/openwrt-ci2/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-qualcommax_ipq807x/linux-6.6.50/.config.override > /home/runner/work/openwrt-ci2/openwrt-ci2/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-qualcommax_ipq807x/linux-6.6.50/.config.set
mv /home/runner/work/openwrt-ci2/openwrt-ci2/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-qualcommax_ipq807x/linux-6.6.50/.config.set /home/runner/work/openwrt-ci2/openwrt-ci2/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-qualcommax_ipq807x/linux-6.6.50/.config.old
grep -v INITRAMFS /home/runner/work/openwrt-ci2/openwrt-ci2/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-qualcommax_ipq807x/linux-6.6.50/.config.old > /home/runner/work/openwrt-ci2/openwrt-ci2/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-qualcommax_ipq807x/linux-6.6.50/.config.set
echo 'CONFIG_INITRAMFS_SOURCE=""' >> /home/runner/work/openwrt-ci2/openwrt-ci2/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-qualcommax_ipq807x/linux-6.6.50/.config.set
echo '# CONFIG_INITRAMFS_FORCE is not set' >> /home/runner/work/openwrt-ci2/openwrt-ci2/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-qualcommax_ipq807x/linux-6.6.50/.config.set
echo "# CONFIG_INITRAMFS_PRESERVE_MTIME is not set" >> /home/runner/work/openwrt-ci2/openwrt-ci2/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-qualcommax_ipq807x/linux-6.6.50/.config.set
rm -rf /home/runner/work/openwrt-ci2/openwrt-ci2/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-qualcommax_ipq807x/modules
cmp -s /home/runner/work/openwrt-ci2/openwrt-ci2/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-qualcommax_ipq807x/linux-6.6.50/.config.set /home/runner/work/openwrt-ci2/openwrt-ci2/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-qualcommax_ipq807x/linux-6.6.50/.config.prev || { cp /home/runner/work/openwrt-ci2/openwrt-ci2/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-qualcommax_ipq807x/linux-6.6.50/.config.set /home/runner/work/openwrt-ci2/openwrt-ci2/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-qualcommax_ipq807x/linux-6.6.50/.config; cp /home/runner/work/openwrt-ci2/openwrt-ci2/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-qualcommax_ipq807x/linux-6.6.50/.config.set /home/runner/work/openwrt-ci2/openwrt-ci2/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-qualcommax_ipq807x/linux-6.6.50/.config.prev; }
export MAKEFLAGS= ; [ -d /home/runner/work/openwrt-ci2/openwrt-ci2/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-qualcommax_ipq807x/linux-6.6.50/user_headers ] || make -C /home/runner/work/openwrt-ci2/openwrt-ci2/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-qualcommax_ipq807x/linux-6.6.50 KCFLAGS="-fmacro-prefix-map=/home/runner/work/openwrt-ci2/openwrt-ci2/openwrt/build_dir/target-aarch64_cortex-a53_musl=target-aarch64_cortex-a53_musl -fno-caller-saves " HOSTCFLAGS="-O2 -I/home/runner/work/openwrt-ci2/openwrt-ci2/openwrt/staging_dir/host/include  -Wall -Wmissing-prototypes -Wstrict-prototypes" CROSS_COMPILE="aarch64-openwrt-linux-musl-" ARCH="arm64" KBUILD_HAVE_NLS=no KBUILD_BUILD_USER="" KBUILD_BUILD_HOST="" KBUILD_BUILD_TIMESTAMP="Mon Sep  9 06:33:20 2024" KBUILD_BUILD_VERSION="0" KBUILD_HOSTLDFLAGS="-L/home/runner/work/openwrt-ci2/openwrt-ci2/openwrt/staging_dir/host/lib" CONFIG_SHELL="bash" V=''  cmd_syscalls=  CC="aarch64-openwrt-linux-musl-gcc" KERNELRELEASE=6.6.50  INSTALL_HDR_PATH=/home/runner/work/openwrt-ci2/openwrt-ci2/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-qualcommax_ipq807x/linux-6.6.50/user_headers headers_install
grep '=[ym]' /home/runner/work/openwrt-ci2/openwrt-ci2/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-qualcommax_ipq807x/linux-6.6.50/.config.set | LC_ALL=C sort | /home/runner/work/openwrt-ci2/openwrt-ci2/openwrt/staging_dir/host/bin/mkhash md5 > /home/runner/work/openwrt-ci2/openwrt-ci2/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-qualcommax_ipq807x/linux-6.6.50/.vermagic
touch /home/runner/work/openwrt-ci2/openwrt-ci2/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-qualcommax_ipq807x/linux-6.6.50/.configured
rm -f /home/runner/work/openwrt-ci2/openwrt-ci2/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-qualcommax_ipq807x/linux-6.6.50/vmlinux /home/runner/work/openwrt-ci2/openwrt-ci2/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-qualcommax_ipq807x/linux-6.6.50/System.map
make -C /home/runner/work/openwrt-ci2/openwrt-ci2/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-qualcommax_ipq807x/linux-6.6.50 KCFLAGS="-fmacro-prefix-map=/home/runner/work/openwrt-ci2/openwrt-ci2/openwrt/build_dir/target-aarch64_cortex-a53_musl=target-aarch64_cortex-a53_musl -fno-caller-saves " HOSTCFLAGS="-O2 -I/home/runner/work/openwrt-ci2/openwrt-ci2/openwrt/staging_dir/host/include  -Wall -Wmissing-prototypes -Wstrict-prototypes" CROSS_COMPILE="aarch64-openwrt-linux-musl-" ARCH="arm64" KBUILD_HAVE_NLS=no KBUILD_BUILD_USER="" KBUILD_BUILD_HOST="" KBUILD_BUILD_TIMESTAMP="Mon Sep  9 06:33:20 2024" KBUILD_BUILD_VERSION="0" KBUILD_HOSTLDFLAGS="-L/home/runner/work/openwrt-ci2/openwrt-ci2/openwrt/staging_dir/host/lib" CONFIG_SHELL="bash" V=''  cmd_syscalls=  CC="aarch64-openwrt-linux-musl-gcc" KERNELRELEASE=6.6.50 Image modules
make[5]: Entering directory '/home/runner/work/openwrt-ci2/openwrt-ci2/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-qualcommax_ipq807x/linux-6.6.50'
  SYNC    include/config/auto.conf.cmd
*
* Restart config...
*
*
* Remoteproc drivers
*
Support for Remote Processor subsystem (REMOTEPROC) [Y/n/?] y
  Remoteproc character device interface (REMOTEPROC_CDEV) [Y/n/?] y
  Qualcomm Technology Inc ADSP Peripheral Image Loader (QCOM_Q6V5_ADSP) [N/m/y/?] n
  Qualcomm Hexagon V5 self-authenticating modem subsystem support (QCOM_Q6V5_MSS) [N/m/y/?] n
  Qualcomm Hexagon v5 Peripheral Authentication Service support (QCOM_Q6V5_PAS) [N/m/y/?] n
make[8]: *** [scripts/kconfig/Makefile:77: syncconfig] Error 1
make[7]: *** [Makefile:697: syncconfig] Error 2
/home/runner/work/openwrt-ci2/openwrt-ci2/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-qualcommax_ipq807x/linux-6.6.50/Makefile:775: include/config/auto.conf.cmd: No such file or directory
make[6]: *** [/home/runner/work/openwrt-ci2/openwrt-ci2/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-qualcommax_ipq807x/linux-6.6.50/Makefile:798: include/config/auto.conf.cmd] Error 2
make[5]: *** [Makefile:234: __sub-make] Error 2
make[4]: *** [Makefile:22: /home/runner/work/openwrt-ci2/openwrt-ci2/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-qualcommax_ipq807x/linux-6.6.50/.modules] Error 2
  Qualcomm Hexagon based MPD model Peripheral Image Loader (QCOM_Q6V5_MPD) [N/m/y/?] (NEW) make[5]: Leaving directory '/home/runner/work/openwrt-ci2/openwrt-ci2/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-qualcommax_ipq807x/linux-6.6.50'
make[4]: Leaving directory '/home/runner/work/openwrt-ci2/openwrt-ci2/openwrt/target/linux/qualcommax'
make[3]: *** [Makefile:11: compile] Error 2
make[3]: Leaving directory '/home/runner/work/openwrt-ci2/openwrt-ci2/openwrt/target/linux'
time: target/linux/compile#1.33#0.50#1.79
    ERROR: target/linux failed to build.
make[2]: *** [target/Makefile:32: target/linux/compile] Error 1
make[2]: Leaving directory '/home/runner/work/openwrt-ci2/openwrt-ci2/openwrt'
make[1]: *** [target/Makefile:25: /home/runner/work/openwrt-ci2/openwrt-ci2/openwrt/staging_dir/target-aarch64_cortex-a53_musl/stamp/.target_compile] Error 2
make[1]: Leaving directory '/home/runner/work/openwrt-ci2/openwrt-ci2/openwrt'
make: *** [/home/runner/work/openwrt-ci2/openwrt-ci2/openwrt/include/toplevel.mk:248: world] Error 2
Error: Process completed with exit code 2.

**Comment by breeze303** [comment]
可以了
