### ISSUE TITLE
大佬，这几个有什么区别吗，希望能指点一二

### ISSUE THREAD

**Issue by cuicanmengxing** [LiBwrt-op/openwrt-6.x#31]
我想要编译一个稳定的固件，这些都能用吗，希望能指点一二，谢谢！
都说是openwrt ipq6000，不知道有没有后门
https://github.com/VIKINGYFY/immortalwrt
https://github.com/LiBwrt-op/openwrt-6.x
https://github.com/JiaY-shi/openwrt/tree/ipq60xx-devel_nss
https://github.com/King-Of-Knights/openwrt-6.x
https://github.com/coolsnowwolf/lede

**Comment by breeze303** [comment]
第一个是基于imm来合并nss等库的
第二个是基于openwrt官方库合并的，同时也在不断整新活
第三个也是op官方但缺少一些机型的支持
第四是也是基于官方目前K佬只同步上游不整活了
第五是大雕的库
话不说绝对，有没有后门咱也不知道，但你用的大部分路由器原厂固件都是基于openwrt魔改的，你说厂商会不会给你留后门，又或者openwrt官方某个bug导致的后门？就连linux都有后门bug，世界上没有绝对安全的系统，只是没有利用价值而已，放心用，大胆用就是了，哪来这么多后门。。。

**Comment by cuicanmengxing** [comment]
好的大佬谢谢
