### ISSUE TITLE
下游打包编译又失败了

### ISSUE THREAD

**Issue by laiyujun** [LiBwrt-op/openwrt-6.x#32]
基于你源码的下游打包编译又出现失败，麻烦修复一下编译错误

**Comment by breeze303** [comment]
升级代码就肯定会伴随bug，莫急莫慌莫催

**Comment by breeze303** [comment]
已修复

**Comment by laiyujun** [comment]
非常支持，可以搞一个测试分支（或叫尝鲜）和一个稳定版本分支，这样就可以既能又能啦！我尝试了很多仓库的代码，总体上都很好，但总是在某些小地方有种说不出的感觉，还是你这个代码用起来感觉最好，所以我也会一直在编译，O(∩_∩)O哈哈~望莫怪

**Comment by breeze303** [comment]
有测试分支，维护起来切来切去太麻烦有时老忘记改的哪个分子就直接push所以还是直接一个main吧
