### ISSUE TITLE
hostapd编译失败

### ISSUE THREAD

**Issue by ZT229** [LiBwrt-op/openwrt-6.x#37]
Applying /home/xt/openwrt-6.x/package/network/services/hostapd/patches/790-APuP-add-ubus-notification-when-a-peer-comes-up.patch using plaintext:
patching file src/ap/apup.c
Hunk #1 succeeded at 31 with fuzz 2 (offset 8 lines).
Hunk #2 FAILED at 153.
1 out of 2 hunks FAILED -- saving rejects to file src/ap/apup.c.rej
patching file src/ap/ubus.c
Hunk #1 FAILED at 2004.
1 out of 1 hunk FAILED -- saving rejects to file src/ap/ubus.c.rej
patching file src/ap/ubus.h
Hunk #1 succeeded at 74 with fuzz 2 (offset 5 lines).
Patch failed!  Please fix /home/xt/openwrt-6.x/package/network/services/hostapd/patches/790-APuP-add-ubus-notification-when-a-peer-comes-up.patch!
make[3]: *** [Makefile:818: /home/xt/openwrt-6.x/build_dir/target-aarch64_cortex-a53_musl/hostapd-wpad-full-openssl/hostapd-2024.09.15~5ace39b0/.prepared_b243f0440a4381c06562cbaed16faa7d_6664517399ebbbc92a37c5bb081b5c53] Error 1
make[3]: Leaving directory '/home/xt/openwrt-6.x/package/network/services/hostapd'
time: package/network/services/hostapd/wpad-full-openssl/compile#0.21#0.53#0.96
    ERROR: package/network/services/hostapd failed to build (build variant: wpad-full-openssl).
make[2]: *** [package/Makefile:177: package/network/services/hostapd/compile] Error 1
make[2]: Leaving directory '/home/xt/openwrt-6.x'
make[1]: *** [package/Makefile:171: /home/xt/openwrt-6.x/staging_dir/target-aarch64_cortex-a53_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/xt/openwrt-6.x'
make: *** [/home/xt/openwrt-6.x/include/toplevel.mk:248: world] Error 2

没选择任何插件和主题，仅选择目标设备然后把目标设备的内存大小设置为512m

**Comment by deanzai** [comment]
等修复吧，自动编译那边也是一样的问题
