### ISSUE TITLE
[bug] redmi ax5 jdcloud wifi 5ghz 无故消失问题

### ISSUE THREAD

**Issue by J9t5K8bX1nY4H2pR** [LiBwrt-op/openwrt-6.x#38]
# 问题描述
- 设备型号 REDMI AX5 JDCLOUD，内存 512MB，电源 12V2A
- 内核版本 6.6.52
- wifi 信道 36，功率 25dbm
- 使用过的加密方式：WPA2-PSK，WPA3-SAE
- wifi 信号在使用中的随机时点消失，有线连接后台，显示 wifi信号0dbm，wifi温度 -255度，断电重启后信号恢复
- 信号消失时，cpu温度均不高于60度
- 分批次购买的两台设备均有wifi消失的问题
- 刷入恩山论坛分享的内核版本4.4.60的固件没有wifi消失的问题
# 相关日志
大量类似于以下的错误
```
[38211.803672] ath11k_warn: 24 callbacks suppressed
[38211.803717] ath11k c000000.wifi: invalid pdev_id 2 in mgmt_rx_event
```
另一台REDMI AX6使用6.6.52固件未发现wifi消失的问题

希望能修复，谢谢

**Comment by breeze303** [comment]
你看看这个库的会不会https://github.com/King-Of-Knights/openwrt-6.x.git

**Comment by wingeva2021** [comment]
360v6也试过信号消失，非常偶然，重启后恢复。

**Comment by wingeva2021** [comment]
> 360v6也试过信号消失，非常偶然，重启后恢复。

另一台当ap的jdc ax1800也是经常掉5G，之前以为是计划任务wifi命令不成功，后面取消计划任务，也一样会无缘无故掉5G信号。

**Comment by breeze303** [comment]
https://github.com/VIKINGYFY/immortalwrt你们再试试这个库看看

**Comment by breeze303** [comment]
> > > https://github.com/VIKINGYFY/immortalwrt 你们再试试这个库看看，因为我很早就不用ipq系列的路由了，代码基本都是靠别人反馈才知道，试试这个库我排除法看看啥问题
> > 
> > 
> > 已刷 源码: https://github.com/VIKINGYFY/immortalwrt hash: 8d13a16464abb8f75dbcbe74b2f0ff7ca5907bff 会及时反馈出现的问题
> 
> 采用相同选项编译，保留配置刷入，已正常使用3天，未出现断wifi事件。

ok那我重新整合仓库吧，可能在不断合并中一些未知的代码插入导致的

**Comment by breeze303** [comment]
> > 目前重新添加了一个新库 https://github.com/breeze303/openwrt-ipq.git 可以试试无线还会不会消失
> 
> 编译失败
> 
> ```
> In file included from /home/runner/work/openwrt-ipqxx-ci/openwrt-ipqxx-ci/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-qualcommax_ipq60xx/linux-6.6.56/arch/arm64/boot/dts/qcom/ipq6018-ax5.dts:5:
> 3602
> /home/runner/work/openwrt-ipqxx-ci/openwrt-ipqxx-ci/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-qualcommax_ipq60xx/linux-6.6.56/arch/arm64/boot/dts/qcom/ipq6018-xiaomi.dtsi:7:10: fatal error: ipq6018-cpufreq.dtsi: No such file or directory
> 3603
>     7 | #include "ipq6018-cpufreq.dtsi"
> 3604
>       |          ^~~~~~~~~~~~~~~~~~~~~~
> 3605
> compilation terminated.
> 3606
> make[5]: *** [Makefile:41: /home/runner/work/openwrt-ipqxx-ci/openwrt-ipqxx-ci/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-qualcommax_ipq60xx/image-ipq6018-ax5.dtb] Error 1
> 3607
> make[5]: Leaving directory '/home/runner/work/openwrt-ipqxx-ci/openwrt-ipqxx-ci/openwrt/target/linux/qualcommax/image'
> 3608
> make[4]: *** [Makefile:23: install] Error 2
> 3609
> make[3]: *** [Makefile:11: install] Error 2
> 3610
> make[4]: Leaving directory '/home/runner/work/openwrt-ipqxx-ci/openwrt-ipqxx-ci/openwrt/target/linux/qualcommax'
> 3611
> make[3]: Leaving directory '/home/runner/work/openwrt-ipqxx-ci/openwrt-ipqxx-ci/openwrt/target/linux'
> 3612
> time: target/linux/install#4.75#2.70#7.40
> 3613
>     ERROR: target/linux failed to build.
> 3614
> make[2]: *** [target/Makefile:32: target/linux/install] Error 1
> 3615
> make[2]: Leaving directory '/home/runner/work/openwrt-ipqxx-ci/openwrt-ipqxx-ci/openwrt'
> 3616
> make[1]: *** [target/Makefile:26: /home/runner/work/openwrt-ipqxx-ci/openwrt-ipqxx-ci/openwrt/staging_dir/target-aarch64_cortex-a53_musl/stamp/.target_install] Error 2
> 3617
> make[1]: Leaving directory '/home/runner/work/openwrt-ipqxx-ci/openwrt-ipqxx-ci/openwrt'
> 3618
> make: *** [/home/runner/work/openwrt-ipqxx-ci/openwrt-ipqxx-ci/openwrt/include/toplevel.mk:248: world] Error 2
> ```

再来一次，我更新了库

**Comment by breeze303** [comment]
> > > > 目前重新添加了一个新库 https://github.com/breeze303/openwrt-ipq.git 可以试试无线还会不会消失
> > > 
> > > 
> > > 编译失败
> > > ```
> > > In file included from /home/runner/work/openwrt-ipqxx-ci/openwrt-ipqxx-ci/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-qualcommax_ipq60xx/linux-6.6.56/arch/arm64/boot/dts/qcom/ipq6018-ax5.dts:5:
> > > 3602
> > > /home/runner/work/openwrt-ipqxx-ci/openwrt-ipqxx-ci/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-qualcommax_ipq60xx/linux-6.6.56/arch/arm64/boot/dts/qcom/ipq6018-xiaomi.dtsi:7:10: fatal error: ipq6018-cpufreq.dtsi: No such file or directory
> > > 3603
> > >     7 | #include "ipq6018-cpufreq.dtsi"
> > > 3604
> > >       |          ^~~~~~~~~~~~~~~~~~~~~~
> > > 3605
> > > compilation terminated.
> > > 3606
> > > make[5]: *** [Makefile:41: /home/runner/work/openwrt-ipqxx-ci/openwrt-ipqxx-ci/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-qualcommax_ipq60xx/image-ipq6018-ax5.dtb] Error 1
> > > 3607
> > > make[5]: Leaving directory '/home/runner/work/openwrt-ipqxx-ci/openwrt-ipqxx-ci/openwrt/target/linux/qualcommax/image'
> > > 3608
> > > make[4]: *** [Makefile:23: install] Error 2
> > > 3609
> > > make[3]: *** [Makefile:11: install] Error 2
> > > 3610
> > > make[4]: Leaving directory '/home/runner/work/openwrt-ipqxx-ci/openwrt-ipqxx-ci/openwrt/target/linux/qualcommax'
> > > 3611
> > > make[3]: Leaving directory '/home/runner/work/openwrt-ipqxx-ci/openwrt-ipqxx-ci/openwrt/target/linux'
> > > 3612
> > > time: target/linux/install#4.75#2.70#7.40
> > > 3613
> > >     ERROR: target/linux failed to build.
> > > 3614
> > > make[2]: *** [target/Makefile:32: target/linux/install] Error 1
> > > 3615
> > > make[2]: Leaving directory '/home/runner/work/openwrt-ipqxx-ci/openwrt-ipqxx-ci/openwrt'
> > > 3616
> > > make[1]: *** [target/Makefile:26: /home/runner/work/openwrt-ipqxx-ci/openwrt-ipqxx-ci/openwrt/staging_dir/target-aarch64_cortex-a53_musl/stamp/.target_install] Error 2
> > > 3617
> > > make[1]: Leaving directory '/home/runner/work/openwrt-ipqxx-ci/openwrt-ipqxx-ci/openwrt'
> > > 3618
> > > make: *** [/home/runner/work/openwrt-ipqxx-ci/openwrt-ipqxx-ci/openwrt/include/toplevel.mk:248: world] Error 2
> > > ```
> > 
> > 
> > 再来一次，我更新了库
> 
> 编译成功，hash: ae21ad1c3081ab086873659a427c63edd70d0776，固件源码: https://github.com/breeze303/openwrt-ipq 升级刷入后，无wifi及web后台无法进入。 用uboot刷入后，也是如此，ssh可连接，执行常见命令返回如下

https://github.com/breeze303/openwrt-ci/blob/main/configs/ipq60xx-all.config
参照这份config配置

**Comment by breeze303** [comment]
能用吗？日志看着没问题

**Comment by breeze303** [comment]
> > 能用吗？日志看着没问题
> 
> 不能，无线没了 ![12345678](https://private-user-images.githubusercontent.com/27670845/376605195-07518e46-4b09-4bd1-ab49-8af147ba46a2.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg5OTcyNDksIm5iZiI6MTcyODk5Njk0OSwicGF0aCI6Ii8yNzY3MDg0NS8zNzY2MDUxOTUtMDc1MThlNDYtNGIwOS00YmQxLWFiNDktOGFmMTQ3YmE0NmEyLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE1VDEyNTU0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQwZGQ2ZDgwZjA4MzE0ODVkNjllOTczNGM0MmY4MDg2OGNmM2RkZWVmNjU4NTM1ZjlkZTc4YjVmNDdlMmRmZjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.P-qXBaseoFysydabXRdKVME89NU2XSXy2jb6aNaQ5aU)

这不有吗，无法开启？

**Comment by breeze303** [comment]
> 感觉这个问题会一直存在，断wifi现象在https://github.com/VIKINGYFY/immortalwrt 的源码上还是出现了，我在ax1800pro jdc, ax5 jdc上都观察到这一现象，5ghz消失，2.4ghz信号存在。
> 
> 我设置了定时任务，检测到5ghz信号消失则自动重启路由器。作为临时解决办法。

我调整了ath11k的版本，测试下看看https://github.com/LiBwrt-op/openwrt-6.x/commit/31a61c7ef7a1e9134c6209a6691c13c40439cbe9

**Comment by wingeva2021** [comment]
> 感觉这个问题会一直存在，断wifi现象在https://github.com/VIKINGYFY/immortalwrt 的源码上还是出现了，我在ax1800pro jdc, ax5 jdc上都观察到这一现象，5ghz消失，2.4ghz信号存在。
> 
> 我设置了定时任务，检测到5ghz信号消失则自动重启路由器。作为临时解决办法。

可以分享下定时任务的写法吗？

**Comment by lutayev** [comment]
Discovered exactly the same issue on my xiaomi ax1800. 5g interface goes down approximately once a day. 
Found similar bug on similar hardware here https://github.com/openwrt/openwrt/issues/13726
Found solution (startup script) here https://github.com/openwrt/openwrt/issues/13562
It looks like works for me - 6 days uptime without wifi goes down.

**Comment by breeze303** [comment]
> Discovered exactly the same issue on my xiaomi ax1800. 5g interface goes down approximately once a day. Found similar bug on similar hardware here [openwrt/openwrt#13726](https://github.com/openwrt/openwrt/issues/13726) Found solution (startup script) here [openwrt/openwrt#13562 (comment)](https://github.com/openwrt/openwrt/issues/13562#issuecomment-1817573570) It looks like works for me - 6 days uptime without wifi goes down.

The script has been modified, please test if it works.

**Comment by breeze303** [comment]
> 感觉这个问题会一直存在，断wifi现象在https://github.com/VIKINGYFY/immortalwrt 的源码上还是出现了，我在ax1800pro jdc, ax5 jdc上都观察到这一现象，5ghz消失，2.4ghz信号存在。
> 
> 我设置了定时任务，检测到5ghz信号消失则自动重启路由器。作为临时解决办法。

这次解决了，你测试下

**Comment by breeze303** [comment]
已修复

**Comment by wingeva2021** [comment]
> 已修复

360v6还是会掉5G，一个小时内掉了2次。5G消失后，luci界面温度为负数，同时无线界面显示5G仍然启用中，只能重启解决。

**Comment by key2p** [comment]
> 感觉这个问题会一直存在，断wifi现象在https://github.com/VIKINGYFY/immortalwrt 的源码上还是出现了，我在ax1800pro jdc, ax5 jdc上都观察到这一现象，5ghz消失，2.4ghz信号存在。
> 
> 我设置了定时任务，检测到5ghz信号消失则自动重启路由器。作为临时解决办法。

ax5 jdc 同样出现, 使用的 https://github.com/LiBwrt-op/openwrt-6.x.git openwrt-24.10 分支
