### ISSUE TITLE
the latest version compile with aria2 failure

### ISSUE THREAD

**Issue by laiyujun** [LiBwrt-op/openwrt-6.x#39]
make[3] -C feeds/luci/libs/luci-lib-ipkg compile
 make[3] -C package/utils/bzip2 compile
 make[3] -C feeds/packages/utils/tar compile
 make[3] -C feeds/istore/luci/luci-app-store compile
 make[3] -C package/libs/openssl compile
 make[3] -C feeds/packages/net/aria2 compile
    ERROR: package/feeds/packages/aria2 failed to build.

**Comment by laiyujun** [comment]
This problem still exists

**Comment by breeze303** [comment]
You've provided too little information to determine the problem.

**Comment by laiyujun** [comment]
[error.log](https://github.com/user-attachments/files/17396195/error.log)
This is the full compile log.
