### ISSUE TITLE
希望增加immortal/wwan-package的支持

### ISSUE THREAD

**Issue by ZT229** [LiBwrt-op/openwrt-6.x#40]
After checking the qmi-wwan related kmods, execute make download, and an error is made to improve no Method download. Then compile the error, because my device has USB, so I don't want to waste this USB interface, want to add the cpe module.

**Comment by breeze303** [comment]
> 同遇到此问题，选择qmi-wwan相关模块后，编译会报如下错误
> 
> ```
> 
> make[3]: Entering directory '/home/runner/work/openwrt-ipqxx-ci/openwrt-ipqxx-ci/openwrt/feeds/packages/kernel/fibocom-qmi-wwan'
> 3559
> mkdir -p /home/runner/work/openwrt-ipqxx-ci/openwrt-ipqxx-ci/openwrt/dl
> 3560
> SHELL= flock /home/runner/work/openwrt-ipqxx-ci/openwrt-ipqxx-ci/openwrt/tmp/.fibocom-qmi-wwan-1.0.5.tar.gz.flock -c '  	echo "ERROR: No download method available"; false'
> 3561
> ERROR: No download method available
> 3562
> make[3]: *** [Makefile:30: /home/runner/work/openwrt-ipqxx-ci/openwrt-ipqxx-ci/openwrt/dl/fibocom-qmi-wwan-1.0.5.tar.gz] Error 1
> 3563
> make[3]: Leaving directory '/home/runner/work/openwrt-ipqxx-ci/openwrt-ipqxx-ci/openwrt/feeds/packages/kernel/fibocom-qmi-wwan'
> 3564
> time: package/feeds/packages/fibocom-qmi-wwan/compile#0.13#0.04#0.15
> 3565
>     ERROR: package/feeds/packages/fibocom-qmi-wwan failed to build.
> ```

不兼容
