### ISSUE TITLE
Use the latest version compile with aria2 failure

### ISSUE THREAD

**Issue by laiyujun** [LiBwrt-op/openwrt-6.x#42]
make[3] -C feeds/luci/libs/luci-lib-ipkg compile
make[3] -C package/utils/bzip2 compile
make[3] -C feeds/packages/utils/tar compile
make[3] -C feeds/istore/luci/luci-app-store compile
make[3] -C package/libs/openssl compile
make[3] -C feeds/packages/net/aria2 compile
ERROR: package/feeds/packages/aria2 failed to build.

Details please see the full log.
[error.log](https://github.com/user-attachments/files/17407675/error.log)

**Comment by laiyujun** [comment]
LibsslARC4Encryptor.cc: In member function 'void aria2::ARC4Encryptor::init(const unsigned char*, size_t)':
LibsslARC4Encryptor.cc:76:33: error: 'EVP_rc4' was not declared in this scope; did you mean 'EVP_md4'?
   76 |   if (EVP_EncryptInit_ex2(ctx_, EVP_rc4(), nullptr, nullptr, params) != 1) {
      |                                 ^~~~~~~
      |                                 EVP_md4
make[7]: *** [Makefile:2644: LibsslARC4Encryptor.lo] Error 1
make[7]: Leaving directory '/home/runner/work/OpenWrt360_6.1/OpenWrt360_6.1/openwrt/build_dir/target-aarch64_cortex-a53_musl/aria2-1.37.0/src'
make[6]: *** [Makefile:2680: all-recursive] Error 1
make[6]: Leaving directory '/home/runner/work/OpenWrt360_6.1/OpenWrt360_6.1/openwrt/build_dir/target-aarch64_cortex-a53_musl/aria2-1.37.0/src'
make[5]: *** [Makefile:558: all-recursive] Error 1
make[5]: Leaving directory '/home/runner/work/OpenWrt360_6.1/OpenWrt360_6.1/openwrt/build_dir/target-aarch64_cortex-a53_musl/aria2-1.37.0'
make[4]: *** [Makefile:469: all] Error 2
make[4]: Leaving directory '/home/runner/work/OpenWrt360_6.1/OpenWrt360_6.1/openwrt/build_dir/target-aarch64_cortex-a53_musl/aria2-1.37.0'
make[3]: Leaving directory '/home/runner/work/OpenWrt360_6.1/OpenWrt360_6.1/openwrt/feeds/packages/net/aria2'
make[3]: *** [Makefile:105: /home/runner/work/OpenWrt360_6.1/OpenWrt360_6.1/openwrt/build_dir/target-aarch64_cortex-a53_musl/aria2-1.37.0/.built] Error 2
time: package/feeds/packages/aria2/compile#0.50#0.11#0.58
    ERROR: package/feeds/packages/aria2 failed to build.
make[2]: *** [package/Makefile:177: package/feeds/packages/aria2/compile] Error 1
make[2]: Leaving directory '/home/runner/work/OpenWrt360_6.1/OpenWrt360_6.1/openwrt'
make[1]: *** [package/Makefile:171: /home/runner/work/OpenWrt360_6.1/OpenWrt360_6.1/openwrt/staging_dir/target-aarch64_cortex-a53_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/runner/work/OpenWrt360_6.1/OpenWrt360_6.1/openwrt'
make: *** [/home/runner/work/OpenWrt360_6.1/OpenWrt360_6.1/openwrt/include/toplevel.mk:248: world] Error 2
Error: Process completed with exit code 2.

**Comment by breeze303** [comment]
done

**Comment by laiyujun** [comment]
> done

This problem still exists

**Comment by breeze303** [comment]
fix

**Comment by laiyujun** [comment]
> fix

加上aria2编译就报错，我把aria2去掉了，不报错了。就这样吧！后面再自行安装试试。Thanks♪(･ω･)ﾉ
