### ISSUE TITLE
Image file jdcloud_ax1800-pro-uImage.itb is too big

### ISSUE THREAD

**Issue by crossxyz** [LiBwrt-op/openwrt-6.x#48]
WARNING: Image file /home/openwrt-6.x/build_dir/target-aarch64_cortex-a53_musl/linux-qualcommax_ipq60xx/jdcloud_ax1800-pro-uImage.itb is too big: 6743832 > 6291456
make[5]: *** [Makefile:42: /home/openwrt-6.x/build_dir/target-aarch64_cortex-a53_musl/linux-qualcommax_ipq60xx/tmp/libwrt-qualcommax-ipq60xx-jdcloud_ax1800-pro-squashfs-sysupgrade.bin] Error 1

内核开了bpf之后变大了编译不成功，有个支持8M的[uboot](https://github.com/wuxiuxiu521/uboot-ipq60xx-build)，请问该如何修改编译openwrt

**Comment by breeze303** [comment]
改mk文件
