### ISSUE TITLE
JDCloud AX6600 配置 160Mhz 怎么无法生效，是不是配置有问题？

### ISSUE THREAD

**Issue by wuruxu** [LiBwrt-op/openwrt-6.x#51]
我的/etc/config/wireless 配置如下
```
config wifi-device 'radio0'
    option type 'mac80211'
    option path 'platform/soc@0/c000000.wifi'
    option band '5g'
    option channel '163'
    option htmode 'HE160'
    option disabled '0'

config wifi-iface 'default_radio0'
    option device 'radio0'
    option network 'lan'
    option mode 'ap'
    option ssid 'OpenWrt_5G'
    option encryption 'sae'
    option key 'xyz'
```

**Comment by wuruxu** [comment]
好，我试试 24.10分支

**Comment by Doanduy09** [comment]
![image](https://github.com/user-attachments/assets/441062ad-bbfb-4fde-971b-112f723febe3)
it works fine, you install as shown

**Comment by wuruxu** [comment]
@Doanduy09 it look fine, would you give me the config file content of your openwrt   (cat /etc/config/wireless)?  Thanks

**Comment by Doanduy09** [comment]
> @Doanduy09 it look fine, would you give me the config file content of your openwrt (cat /etc/config/wireless)? Thanks

![image](https://github.com/user-attachments/assets/a06526a8-60c4-400e-874a-bb4ca18a3044)



config wifi-device 'radio0'
	option type 'mac80211'
	option path 'platform/soc@0/c000000.wifi'
	option band '5g'
	option channel '149'
	option htmode 'HE80'
	option country 'US'
	option cell_density '0'

config wifi-iface 'default_radio0'
	option device 'radio0'
	option network 'lan'
	option mode 'ap'
	option ssid 'OpenWrt'
	option encryption 'none'

config wifi-device 'radio1'
	option type 'mac80211'
	option path 'platform/soc@0/c000000.wifi+1'
	option band '2g'
	option channel '1'
	option htmode 'HE20'

config wifi-iface 'default_radio1'
	option device 'radio1'
	option network 'lan'
	option mode 'ap'
	option ssid 'OpenWrt'
	option encryption 'none'

config wifi-device 'radio2'
	option type 'mac80211'
	option path 'soc@0/20000000.pci/pci0000:00/0000:00:00.0/0000:01:00.0'
	option band '5g'
	option channel '36'
	option htmode 'HE160'
	option country 'US'
	option cell_density '0'
	option txpower '30'

config wifi-iface 'default_radio2'
	option device 'radio2'
	option network 'lan'
	option mode 'ap'
	option ssid 'OpenWrt test'
	option encryption 'none'

**Comment by wuruxu** [comment]
@breeze303   why my compile rom only have two radio, which config need enable ? Thanks
```
root@LibWrt:/etc/config# wifi config
root@LibWrt:/etc/config# cat wireless

config wifi-device 'radio0'
	option type 'mac80211'
	option path 'platform/soc@0/c000000.wifi'
	option band '5g'
	option channel '36'
	option htmode 'HE80'
	option disabled '1'

config wifi-iface 'default_radio0'
	option device 'radio0'
	option network 'lan'
	option mode 'ap'
	option ssid 'OpenWrt'
	option encryption 'none'

config wifi-device 'radio1'
	option type 'mac80211'
	option path 'platform/soc@0/c000000.wifi+1'
	option band '2g'
	option channel '1'
	option htmode 'HE20'
	option disabled '1'

config wifi-iface 'default_radio1'
	option device 'radio1'
	option network 'lan'
	option mode 'ap'
	option ssid 'OpenWrt'
	option encryption 'none'
```

**Comment by breeze303** [comment]
> @breeze303 why my compile rom only have two radio, which config need enable ? Thanks
> 
> ```
> root@LibWrt:/etc/config# wifi config
> root@LibWrt:/etc/config# cat wireless
> 
> config wifi-device 'radio0'
> 	option type 'mac80211'
> 	option path 'platform/soc@0/c000000.wifi'
> 	option band '5g'
> 	option channel '36'
> 	option htmode 'HE80'
> 	option disabled '1'
> 
> config wifi-iface 'default_radio0'
> 	option device 'radio0'
> 	option network 'lan'
> 	option mode 'ap'
> 	option ssid 'OpenWrt'
> 	option encryption 'none'
> 
> config wifi-device 'radio1'
> 	option type 'mac80211'
> 	option path 'platform/soc@0/c000000.wifi+1'
> 	option band '2g'
> 	option channel '1'
> 	option htmode 'HE20'
> 	option disabled '1'
> 
> config wifi-iface 'default_radio1'
> 	option device 'radio1'
> 	option network 'lan'
> 	option mode 'ap'
> 	option ssid 'OpenWrt'
> 	option encryption 'none'
> ```

ath11k-firmware-qcn9074

**Comment by wuruxu** [comment]
好 非常感谢
