### ISSUE TITLE
24.10分支报错

### ISSUE THREAD

**Issue by qwerttvv** [LiBwrt-op/openwrt-6.x#53]
更新feed时候

Collecting package info: feeds/nss_packages/wwan/app/luci-proto-quectel
Collecting package info: feeds/nss_packages/wwan/app/quectel-cm
Collecting package info: feeds/nss_packages/wwan/driver/quectel_MHI
Collecting package info: feeds/nss_packages/wwan/driver/quectel_QMI_WWAN
Collecting package info: merging...

Collecting package info: done
Collecting target info: merging...

Collecting target info: doneCreate index file './feeds/sqm_scripts_nss.index' 
find: ‘feeds/sqm_scripts_nss’: No such file or directory

Collecting package info: merging...

Collecting package info: donefind: ‘feeds/sqm_scripts_nss’: No such file or directory

Collecting target info: merging...

Collecting target info: done
Error: Process completed with exit code 1.

**Comment by wang33winner** [comment]
先检查下git status是否clean，有无自己修改内容

**Comment by wang33winner** [comment]
你的有一个步骤是`[ -e $FEEDS_CONF ] && mv $FEEDS_CONF openwrt/feeds.conf.default`这里你要自己检查下你的脚本，我看你好像是ZN M2吗？我用这个设备可以编译的，主要是menuconfig中3个内存相关选择（内核模块：Wireless Drivers——memory profile——512M
内核模块：Network Devices——komd-qca-nss-drv——configuration——512M
IPQ选项：memory profile-512M）都选择512
你那个自定义feeds报错，你要检查下你的自定义feeds内容
